"""Replay handles source DBs whose rows have NULL ``deduplication_key``.

Older PersistentDriver runs (and any run whose scraper opted out of
deduplication) can land rows in the DB without a dedup_key. The replay
driver derives a stable fallback key from the row's stored URL + body
for those rows; the lookup side does the same on a yielded Request's
serialized form when its own key doesn't hit the index.

This test exercises that path end-to-end: it builds a normal source DB,
NULLs every ``deduplication_key`` column in it, then replays. Without
the fallback, every request misses and ends up pending; with it,
results match the original.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest

from kent.data_types import HttpMethod, HTTPRequestParams, Request
from kent.driver.local_only_driver import LocalOnlyDriver
from kent.driver.local_only_driver.source_index import (
    SourceIndex,
    fallback_replay_key,
    fallback_replay_key_for_request,
    serialize_url_and_body,
)
from tests.conftest import AioHttpTestServer
from tests.drivers.local_only.conftest import (
    make_bug_court_scraper,
    read_completed_dedup_keys,
    read_result_data_json,
    run_with_persistent_driver,
)


def _null_all_dedup_keys(db_path: Path) -> int:
    """Wipe every Request row's ``deduplication_key`` to NULL.

    Returns the number of rows affected.
    """
    conn = sqlite3.connect(str(db_path))
    cur = conn.execute("UPDATE requests SET deduplication_key = NULL")
    conn.commit()
    affected = cur.rowcount
    conn.close()
    return affected


def test_fallback_replay_key_is_stable_across_sides() -> None:
    """Both ends compute the same fallback for the same logical request.

    The index reads a stored URL (with params already merged in) + body.
    The lookup re-serializes a fresh ``HTTPRequestParams`` the same way.
    """
    http_params = HTTPRequestParams(
        method=HttpMethod.GET,
        url="http://example.com/path",
        params={"q": "value", "page": "2"},
        data=b"payload",
    )
    expected_url, expected_body = serialize_url_and_body(http_params)
    assert fallback_replay_key(
        expected_url, expected_body
    ) == fallback_replay_key_for_request(http_params)


def test_fallback_replay_key_namespace_disjoint_from_real_keys() -> None:
    """The fallback prefix keeps its hex digest out of `_generate_deduplication_key`'s space.

    Both produce 64-char hex SHA256, but the inputs differ in their
    leading bytes, so two distinct strings hash to distinct outputs.
    """
    http_params = HTTPRequestParams(
        method=HttpMethod.GET, url="http://example.com/p"
    )
    fallback = fallback_replay_key_for_request(http_params)
    # The default key generated by BaseRequest.__post_init__ for the
    # same HTTP params.
    real_key = Request(request=http_params, continuation="x").deduplication_key
    assert isinstance(real_key, str)
    assert fallback != real_key


def test_source_index_uses_fallback_for_null_dedup_rows(
    tmp_path: Path,
) -> None:
    """A row with NULL dedup_key enters the index under its fallback hash."""
    import zstandard as zstd

    db = tmp_path / "nullkeys.db"
    conn = sqlite3.connect(str(db))
    conn.executescript(
        """
        CREATE TABLE requests (
            id INTEGER PRIMARY KEY,
            deduplication_key TEXT,
            response_status_code INTEGER,
            content_compressed BLOB,
            compression_dict_id INTEGER,
            response_headers_json TEXT,
            response_url TEXT,
            url TEXT,
            method TEXT,
            headers_json TEXT,
            cookies_json TEXT,
            body BLOB,
            continuation TEXT,
            current_location TEXT,
            accumulated_data_json TEXT,
            permanent_json TEXT,
            expected_type TEXT,
            verify TEXT,
            bypass_rate_limit INTEGER DEFAULT 0,
            request_type TEXT,
            parent_request_id INTEGER,
            completed_at_ns INTEGER,
            created_at_ns INTEGER,
            priority INTEGER DEFAULT 9,
            hateoas BOOLEAN
        );
        CREATE TABLE errors (
            id INTEGER PRIMARY KEY,
            request_id INTEGER,
            error_type TEXT,
            is_resolved BOOLEAN DEFAULT 0
        );
        CREATE TABLE archived_files (id INTEGER PRIMARY KEY);
        CREATE TABLE compression_dicts (
            id INTEGER PRIMARY KEY,
            dictionary_data BLOB
        );
        CREATE TABLE run_metadata (id INTEGER PRIMARY KEY, scraper_name TEXT);
        """
    )
    compressed = zstd.ZstdCompressor().compress(b"<html></html>")
    conn.execute(
        """
        INSERT INTO requests (
            deduplication_key, response_status_code, content_compressed,
            response_headers_json, response_url, url, method, body,
            continuation, completed_at_ns, created_at_ns, request_type
        ) VALUES (NULL, 200, ?, '{}', 'http://x/path?k=v', 'http://x/path?k=v',
                  'GET', NULL, 'parse', 1, 1, 'navigating')
        """,
        (compressed,),
    )
    conn.commit()
    conn.close()

    idx = SourceIndex(source_db_paths=[db])
    try:
        # The row should be reachable under its fallback key.
        fallback = fallback_replay_key("http://x/path?k=v", None)
        entry = idx.lookup(fallback)
        assert entry is not None
        # Lookups using a non-existent real key still miss.
        assert idx.lookup("nonexistent-real-key") is None
    finally:
        idx.close()


@pytest.mark.asyncio
async def test_replay_against_source_with_all_null_dedup_keys(
    bug_court_server: AioHttpTestServer, tmp_path: Path
) -> None:
    """End-to-end: replay matches every request even when source dedup_keys are NULL."""
    source_db = tmp_path / "source.db"
    out_db = tmp_path / "out.db"

    await run_with_persistent_driver(
        make_bug_court_scraper(bug_court_server.url), source_db
    )
    # The source DB now has dedup_keys populated by BaseRequest.__post_init__.
    # Strip them all to simulate an older DB or a scraper that bypassed
    # auto-population.
    affected = _null_all_dedup_keys(source_db)
    assert affected > 0, "Persistent run produced no rows to NULL"

    baseline_results = sorted(
        await read_result_data_json(source_db),
        key=lambda r: r.get("docket", ""),
    )

    async with LocalOnlyDriver.open(
        scraper=make_bug_court_scraper(bug_court_server.url),
        db_path=out_db,
        source_db_paths=[source_db],
        miss_policy="raise",
        mode="curr-error-free",
        num_workers=2,
        enable_monitor=False,
    ) as driver:
        await driver.run(setup_signal_handlers=False)

    replay_results = sorted(
        await read_result_data_json(out_db), key=lambda r: r.get("docket", "")
    )
    assert replay_results == baseline_results
    # The replay's output DB has its own (auto-populated) dedup_keys —
    # those rows went through enqueue normally and the schema migration
    # is current.
    assert await read_completed_dedup_keys(out_db)
